In [ ]:
!nvidia-smi

Thu Nov 12 16:46:13 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.32.00    Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   38C    P8     7W /  75W |      0MiB /  7611MiB |      0%      Default |
|                               |                      |                 ERR! |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
from __future__ import absolute_import, division,print_function, unicode_literals

try:
  !pip uninstall tb-nightly tensorboardx tensorboardx
  !pip install tf-nightly
except:
  pass
import tensorflow as tf
import os
import datetime
import tensorflow_datasets as tfds

%load_ext tensorboard

     |████████████████████████████████| 395.8MB 43kB/s 
     |████████████████████████████████| 1.3MB 44.9MB/s 
     |████████████████████████████████| 3.8MB 45.8MB/s 
     |████████████████████████████████| 10.6MB 147kB/s 
     |████████████████████████████████| 471kB 44.1MB/s 
     |████████████████████████████████| 14.5MB 251kB/s 
ERROR: tensorflow 2.3.0 has requirement numpy<1.19.0,>=1.16.0, but you'll have numpy 1.19.4 which is incompatible.
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.
  Found existing installation: protobuf 3.12.4
    Uninstalling protobuf-3.12.4:
      Successfully uninstalled protobuf-3.12.4
  Found existing installation: grpcio 1.33.2
    Uninstalling grpcio-1.33.2:
      Successfully uninstalled grpcio-1.33.2
  Found existing installation: numpy 1.18.5
    Uninstalling numpy-1.18

In [ ]:
import tensorflow as tf
import os
import datetime
import tensorflow_datasets as tfds

%load_ext tensorboard
import pkg_resources

for entry_point in pkg_resources.iter_entry_points("tensorboard_plugins"):
  print(entry_point.dist)

tensorboard 2.3.0
tensorboard-plugin-wit 1.7.0


In [ ]:
!rm -r /usr/local/lib/python3.6/dist_packages/tensorboardcolab-0.0.22.dist-info

rm: cannot remove '/usr/local/lib/python3.6/dist_packages/tensorboardcolab-0.0.22.dist-info': No such file or directory


In [ ]:
print(tf.__version__)

2.3.0


In [ ]:
tf.config.experimental.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:XLA_CPU:0', device_type='XLA_CPU'),
 PhysicalDevice(name='/physical_device:XLA_GPU:0', device_type='XLA_GPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
dataset, info=tfds.load("amazon_us_reviews/Mobile_Electronics_v1_00" , with_info=True)
train_dataset=dataset['train']

Shuffling and writing examples to /root/tensorflow_datasets/amazon_us_reviews/Mobile_Electronics_v1_00/0.1.0.incompleteMKBRFB/amazon_us_reviews-train.tfrecord


Dataset amazon_us_reviews downloaded and prepared to /root/tensorflow_datasets/amazon_us_reviews/Mobile_Electronics_v1_00/0.1.0. Subsequent calls will reuse this data.


In [ ]:
info


tfds.core.DatasetInfo(
    name='amazon_us_reviews',
    version=0.1.0,
    description='Amazon Customer Reviews (a.k.a. Product Reviews) is one of Amazons iconic products. In a period of over two decades since the first review in 1995, millions of Amazon customers have contributed over a hundred million reviews to express opinions and describe their experiences regarding products on the Amazon.com website. This makes Amazon Customer Reviews a rich source of information for academic researchers in the fields of Natural Language Processing (NLP), Information Retrieval (IR), and Machine Learning (ML), amongst others. Accordingly, we are releasing this data to further research in multiple disciplines related to understanding customer product experiences. Specifically, this dataset was constructed to represent a sample of customer evaluations and opinions, variation in the perception of a product across geographical regions, and promotional intent or bias in reviews.

Over 130+ million cus

In [ ]:
print(train_dataset)

<PrefetchDataset shapes: {data: {customer_id: (), helpful_votes: (), marketplace: (), product_category: (), product_id: (), product_parent: (), product_title: (), review_body: (), review_date: (), review_headline: (), review_id: (), star_rating: (), total_votes: (), verified_purchase: (), vine: ()}}, types: {data: {customer_id: tf.string, helpful_votes: tf.int32, marketplace: tf.string, product_category: tf.string, product_id: tf.string, product_parent: tf.string, product_title: tf.string, review_body: tf.string, review_date: tf.string, review_headline: tf.string, review_id: tf.string, star_rating: tf.int32, total_votes: tf.int32, verified_purchase: tf.int64, vine: tf.int64}}>


In [ ]:
len(list(train_dataset))

104975

In [ ]:
BUFFER_SIZE=30000
BATCH_SIZE=128


In [ ]:
train_dataset=train_dataset.shuffle(BUFFER_SIZE,reshuffle_each_iteration=False)

In [ ]:
for reviews in train_dataset.take(2):
  print(reviews)

{'data': {'customer_id': <tf.Tensor: shape=(), dtype=string, numpy=b'10714201'>, 'helpful_votes': <tf.Tensor: shape=(), dtype=int32, numpy=0>, 'marketplace': <tf.Tensor: shape=(), dtype=string, numpy=b'US'>, 'product_category': <tf.Tensor: shape=(), dtype=string, numpy=b'Mobile_Electronics'>, 'product_id': <tf.Tensor: shape=(), dtype=string, numpy=b'B004VY74PU'>, 'product_parent': <tf.Tensor: shape=(), dtype=string, numpy=b'646570221'>, 'product_title': <tf.Tensor: shape=(), dtype=string, numpy=b'Light Pink Zebra Striped Hard Case for Apple iPod Touch 4G (4th Generation)'>, 'review_body': <tf.Tensor: shape=(), dtype=string, numpy=b"this was super cute but broke very easy, it was bought for my 18 year old so it wasn't a small child. the had cases crack so it's not the seller's fault or this items alones fault...it's all hard plastic ones because the other ones i bought did the same thing.">, 'review_date': <tf.Tensor: shape=(), dtype=string, numpy=b'2013-07-09'>, 'review_headline': <tf.

In [ ]:
for reviews in train_dataset.take(10):
  reviews_text=reviews["data"]
  print(reviews_text.get("review_body").numpy())
  print(reviews_text.get("star_rating").numpy())
  print(tf.where(reviews_text.get("star_rating")>3,1,0).numpy())

b"this was super cute but broke very easy, it was bought for my 18 year old so it wasn't a small child. the had cases crack so it's not the seller's fault or this items alones fault...it's all hard plastic ones because the other ones i bought did the same thing."
2
0
b'Added this to our company truck and the quality is amazing for the price... Took a little bit to understand the menus but once we got it up works great.....well worth money'
5
1
b'Great earphones.'
5
1
b"After my son's 3DS took a dip in some water it quit working properly.  I was able to access the square trade warranty that I purchased with the 3DS two years ago.  In less than a week since the incident I replaced both the 3DS and the warranty.  Square Trade is extremely efficient- they emailed me mailing labels and then an amazon gift card that was actually 5% more than the amount originally paid for the 3DS.  You can't beat that.  I highly recommend Square Trade on all counts- for efficiency, easy use (everything was h

In [ ]:
tokenizer=tfds.deprecated.text.Tokenizer()

vocabluary_set=set()

for _,reviews in train_dataset.enumerate():
  reviews_text=reviews["data"]
  reviews_tokens=tokenizer.tokenize(reviews_text.get('review_body').numpy())
  vocabluary_set.update(reviews_tokens)
vocab_size=len(vocabluary_set)
vocab_size

73738

In [ ]:
encoder=tfds.deprecated.text.TokenTextEncoder(vocabluary_set)

In [ ]:
print(vocabluary_set)

{'unpractical', 'Full', 'landfill', 'NiCd', 'KOBO', 'fuschia', 'Duet', 'dj', 'lookls', 'impossable', 'Pocketcasts', 'Urban', 'F50', 'messed', 'MELTS', 'shortlisted', 'Okayed', 'expletive', 'rude', 'permitted', 'braided', 'constucted', 'betatched', '200W', '65mm', 'PGS', 'contingency', 'oridginally', 'steelie', '70mm', 'Memory', 'Birdhouse', 'famly', 'Lilliputian', '65W', 'particularmente', 'Songza', 'BACKGROUND', 'km', 'Mobi', 'supplement', 'acessorized', 'efficent', 'enjoys', 'backfeed', 'resealed', 'criticizing', 'MiB', 'R', 'inpot', 'bios', 'debris', '121', 'carabiners', 'many', 'JX500', 'Wave', 'B001BI4QUK', 'istructions', 'bargin', '931', 'MDX', '6X9s', 'Graeme', 'SHATTERED', 'deployment', 'heel', 'agreeded', 'wasnt', 'entertainment', 'intents', 'fills', 'Somne', 'Sattelite', 'e46', 'turntablist', 'sup', 'eargels', 'panniers', 'Kiq', 'grind', 'tope', 'FORMS', 'harvest', 'certificates', 'dataport', 'Bogota', '446MHz', 'slap', '28ver', 'STICKERS', 'tuggeda', 'anoffer', 'disappear', 

In [ ]:
for reviews in train_dataset.take(5):
  reviews_text=reviews["data"]
  print(reviews_text.get("review_body").numpy())
  encoded_example=encoder.encode(reviews_text.get("review_body").numpy())
  print(encoded_example)
  

b"this was super cute but broke very easy, it was bought for my 18 year old so it wasn't a small child. the had cases crack so it's not the seller's fault or this items alones fault...it's all hard plastic ones because the other ones i bought did the same thing."
[33005, 32090, 1163, 50405, 47795, 10172, 60052, 69819, 29373, 32090, 278, 6830, 55955, 65903, 61811, 7393, 11984, 29373, 73239, 14020, 4118, 48140, 36341, 35694, 11140, 70115, 53699, 11984, 29373, 41539, 49332, 35694, 45517, 41539, 59137, 10483, 33005, 59783, 8081, 59137, 29373, 41539, 62246, 15081, 10629, 27749, 11906, 35694, 8151, 27749, 32744, 278, 11441, 35694, 1290, 31751]
b'Added this to our company truck and the quality is amazing for the price... Took a little bit to understand the menus but once we got it up works great.....well worth money'
[37845, 33005, 15984, 52356, 30613, 37665, 53354, 35694, 52102, 63392, 54783, 6830, 35694, 10730, 56873, 4118, 37167, 28123, 15984, 1894, 35694, 40154, 47795, 726, 61532, 44657, 

In [ ]:
for idx in encoded_example:
  print(f'{encoder.decode([idx])}==>{idx}')

Worked==>8992
perfectly==>28709
no==>13703
problems==>43951
Ipod==>40977
can==>38868
be==>32946
accessed==>58909
and==>53354
charged==>32544
correctly==>71476
A==>72926
bit==>28123
more==>29125
expensive==>8987
but==>47795
no==>13703
sparks==>61395
as==>60630
mentioned==>13751
in==>26675
other==>8151
reviews==>25673


In [ ]:
def encode(text_tensor, label_tensor):
  encoded_text=encoder.encode(text_tensor.numpy())
  label=tf.where(label_tensor>3,1,0)
  return encoded_text,label

In [ ]:
def encode_map_fn(tensor):
  text=tensor["data"].get('review_body')
  label=tensor["data"].get('star_rating')

  encoded_text,label=tf.py_function(encode,inp=[text,label] ,Tout=(tf.int64,tf.int32))

  encoded_text.set_shape([None])
  label.set_shape([])

  return encoded_text,label

In [ ]:
ar_encoded_data=train_dataset.map(encode_map_fn)

In [ ]:
for f0,f1 in ar_encoded_data.take(2):
  print(f0)
  print(f1)

tf.Tensor(
[33005 32090  1163 50405 47795 10172 60052 69819 29373 32090   278  6830
 55955 65903 61811  7393 11984 29373 73239 14020  4118 48140 36341 35694
 11140 70115 53699 11984 29373 41539 49332 35694 45517 41539 59137 10483
 33005 59783  8081 59137 29373 41539 62246 15081 10629 27749 11906 35694
  8151 27749 32744   278 11441 35694  1290 31751], shape=(56,), dtype=int64)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(
[37845 33005 15984 52356 30613 37665 53354 35694 52102 63392 54783  6830
 35694 10730 56873  4118 37167 28123 15984  1894 35694 40154 47795   726
 61532 44657 29373 40995 70192  8745 46667 14026 69241], shape=(33,), dtype=int64)
tf.Tensor(1, shape=(), dtype=int32)


In [ ]:
take_size=10000
train_data=ar_encoded_data.skip(take_size).shuffle(BUFFER_SIZE)
train_data=train_data.padded_batch(BATCH_SIZE)

test_data=ar_encoded_data.take(take_size)
test_data=test_data.padded_batch(BATCH_SIZE)


In [ ]:
vocab_size+=1

In [ ]:
sample_text , sample_labels=next(iter(test_data))

sample_text[0] , sample_labels[0]

(<tf.Tensor: shape=(529,), dtype=int64, numpy=
 array([33005, 32090,  1163, 50405, 47795, 10172, 60052, 69819, 29373,
        32090,   278,  6830, 55955, 65903, 61811,  7393, 11984, 29373,
        73239, 14020,  4118, 48140, 36341, 35694, 11140, 70115, 53699,
        11984, 29373, 41539, 49332, 35694, 45517, 41539, 59137, 10483,
        33005, 59783,  8081, 59137, 29373, 41539, 62246, 15081, 10629,
        27749, 11906, 35694,  8151, 27749, 32744,   278, 11441, 35694,
         1290, 31751,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,  

In [ ]:
for f0,f1 in test_data.take(10):
  print(tf.unique_with_counts(f1)[2].numpy())

[40 88]
[96 32]
[85 43]
[48 80]
[79 49]
[47 81]
[86 42]
[87 41]
[43 85]
[88 40]


In [ ]:
model=tf.keras.Sequential()
model.add(tf.keras.layers.Embedding(vocab_size,128))
model.add(tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(128,return_sequences=True)))
#model.add(tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(64,return_sequences=True)))
model.add(tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(64)))
for units in [64,64]:
  model.add(tf.keras.layers.Dense(units,activation='relu'))
model.add(tf.keras.layers.Dense(1))



In [ ]:
!rm -r /tmp/logs

rm: cannot remove '/tmp/logs': No such file or directory


In [ ]:
logdir=os.path.join('/tmp/logs' , datetime.datetime.now().strftime("%Y%m%d-%H%M%S"))
tensorboard=tf.keras.callbacks.TensorBoard(logdir,histogram_freq=1)
checkpointer=tf.keras.callbacks.ModelCheckpoint(filepath='/tmp/sentimentanalysis.hdf5',verbose=1,save_best_only=True)
model.compile(loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
              optimizer="adam",
              metrics=["accuracy"])


In [ ]:
history=model.fit(train_data,epochs=4, validation_data=test_data,callbacks=[tensorboard,checkpointer])

Epoch 1/4
  1/742 [..............................] - ETA: 0s - loss: 0.6959 - accuracy: 0.2969WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/summary_ops_v2.py:1277: stop (from tensorflow.python.eager.profiler) is deprecated and will be removed after 2020-07-01.
Instructions for updating:
use `tf.profiler.experimental.stop` instead.


Instructions for updating:
use `tf.profiler.experimental.stop` instead.


742/742 [==============================] - ETA: 0s - loss: 0.3360 - accuracy: 0.8476
Epoch 00001: val_loss improved from inf to 0.27316, saving model to /tmp/sentimentanalysis.hdf5
742/742 [==============================] - 338s 456ms/step - loss: 0.3360 - accuracy: 0.8476 - val_loss: 0.2732 - val_accuracy: 0.8803
Epoch 2/4
742/742 [==============================] - ETA: 0s - loss: 0.2197 - accuracy: 0.9099
Epoch 00002: val_loss improved from 0.27316 to 0.27281, saving model to /tmp/sentimentanalysis.hdf5
742/742 [==============================] - 334s 451ms/step - loss: 0.2197 - accuracy: 0.9099 - val_loss: 0.2728 - val_accuracy: 0.8814
Epoch 3/4
742/742 [==============================] - ETA: 0s - loss: 0.1660 - accuracy: 0.9349
Epoch 00003: val_loss did not improve from 0.27281
742/742 [==============================] - 331s 446ms/step - loss: 0.1660 - accuracy: 0.9349 - val_loss: 0.2948 - val_accuracy: 0.8843
Epoch 4/4
742/742 [==============================] - ETA: 0s - loss: 0.12

In [ ]:
!ls -alrt /tmp/*.hdf5

-rw-r--r-- 1 root root 118632960 Nov 12 17:10 /tmp/sentimentanalysis.hdf5


In [ ]:
model.save('/tmp/final_sentiment_analysis.hdf5')

In [ ]:
eval_loss , eval_acc=model.evaluate(test_data)
print(eval_loss,eval_acc)

79/79 [==============================] - 17s 210ms/step - loss: 0.3291 - accuracy: 0.8822
0.3290700316429138 0.8822000026702881


In [ ]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, None, 128)         9438592   
_________________________________________________________________
bidirectional_4 (Bidirection (None, None, 256)         263168    
_________________________________________________________________
bidirectional_5 (Bidirection (None, 128)               164352    
_________________________________________________________________
dense_3 (Dense)              (None, 64)                8256      
_________________________________________________________________
dropout (Dropout)            (None, 64)                0         
_________________________________________________________________
dense_4 (Dense)              (None, 64)                4160      
_________________________________________________________________
dense_5 (Dense)              (None, 1)                